### ISSUE TITLE
Interesting behaviour regarding double-height text

### ISSUE THREAD

**Issue by Sophira** [simonlaszcz/vidtex#2]
First of all - thank you so much for creating this client! It's literally the only F/OSS videotex software available for Linux that I can find. I've only really gotten into Viewdata over TCP very recently but I love this client - it's made things a lot more accessible for me.

For some reason, vidtex (using the Galax font) sometimes appears to have trouble rendering double-height text. I'm not entirely sure why - I don't know enough about the protocol to know, yet, and most double-height text renders properly. However, I do have some ideas. (The following screenshots are taken using the [Sakura](https://www.pleyades.net/david/projects/sakura) terminal emulator, though I have observed the same happening on xterm as well.)

An example of the problem can be seen on the TEEFAX-to-Viewdata server at **teletext.matrixnetwork.co.uk** port 6502. Going to page 165 in vidtex using the Galax Mode 7 font and the `--galax` option renders the page as follows:

![p165 rendered in vidtex](https://github.com/simonlaszcz/vidtex/assets/1545217/e3eef236-6a46-45df-befa-f49983b66b29)

Going to the same page in the binary TELSTAR Linux client shows seems to be the correct rendering:

![p165 rendered in TELSTAR](https://github.com/simonlaszcz/vidtex/assets/1545217/432ca05c-0228-441b-8038-6fac52e5e198)

Another page which fails in a similar way is p163, which also has an interesting glitch which may be part of why this issue is occurring. In vidtex, it looks like this:

![p163 rendered in vidtex](https://github.com/simonlaszcz/vidtex/assets/1545217/2e794c81-04f1-41f3-a837-89706dd045e7)

If you look closely, the topmost version of the line (the one that's cut off) actually has a typo - the "m" in "Batman" is an "n", so it doesn't match the bottom line. Rendering the same page in TELSTAR makes this clearer and shows that TELSTAR ignores the bottom line:

![p163 rendered in TELSTAR](https://github.com/simonlaszcz/vidtex/assets/1545217/afa06c95-0383-4d94-b828-5de4e5be194b)

I do not know if this is the correct rendering or not, but I do wonder - is vidtex expecting the two lines to be exactly the same and restarting the double-height render process if they aren't?

I don't know enough about the Videotex standards to know whether it's the correct behaviour to do this or to ignore the second line as TELSTAR seems to, but since I couldn't find an issue about this here I thought it would be appropriate to make one.

Thank you again for this client!

**Comment by simonlaszcz** [comment]
Hi Sophira, thanks for your kind words and for raising this issue. Your hunch sounds very likely; for some reason the second line of the double height line pair is being rendered when it shouldn't. I'll look into this ASAP

**Comment by simonlaszcz** [comment]
This has now been fixed. v.1.3.0 is now available and also contains a couple of small new features.
Thanks for using the program :-)
